spring:
  datasource:
    url: jdbc:postgresql://switchback.proxy.rlwy.net:14167/railway
    username: postgres
    password: wEXgyzdlidUJddmYTwDZmRVGMZLviqma
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect